### ISSUE TITLE
The extra code causes errors in localized version

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/www-l10n#349]
Remove **"** in [`<a { $top }">`](https://github.com/mozilla-l10n/www-l10n/blob/c88aad1f8df6b8258b779a0f0aa46ca93b0c7f4f/en/firefox/features/customize-2023.ftl#L27C60-L27C60 ) - this is causing some linter errors in the vendor's delivery but somehow translation from the Pontoon is fine.

Please update the string. The string ID can remain the same. 

@craigcook

**Comment by flodolo** [comment]
> Remove **"** in [`<a { $top }">`](https://github.com/mozilla-l10n/www-l10n/blob/c88aad1f8df6b8258b779a0f0aa46ca93b0c7f4f/en/firefox/features/customize-2023.ftl#L27C60-L27C60) - this is causing some linter errors in the vendor's delivery but somehow translation from the Pontoon is fine.

There is an extra double quote after the variable that we both missed in review (not that it's easy to spot).

> Please update the string. The string ID can remain the same.

[All other locales](https://transvision.flod.org/string/?entity=mozilla_org/en/firefox/features/customize-2023.ftl:features-customize-you-can-find-more-free-custom&repo=mozilla_org) have the same error as English, it's showing up in the linter just because Smartling converts it to an HTML entity.

If we fix English, we need a new ID to update all other locales, or to manually fix all strings.
